openapi: 3.0.0
info:
  title: Advanced Defense & Sensor Platform API
  version: 1.0.0
  description: API documentation for the Advanced Defense & Sensor Platform backend
servers:
  - url: http://localhost:4000
paths:
  /api/sensor:
    post:
      summary: Submit real sensor data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                type:
                  type: string
                  enum: [radar, seismic, infrared]
                value:
                  type: number
                event:
                  type: object
                  nullable: true
                meta:
                  type: object
                  nullable: true
                timestamp:
                  type: integer
              required: [id, type, value, timestamp]
      responses:
        '200':
          description: Success
  /api/login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required: [username, password]
      responses:
        '200':
          description: Authenticated
  /api/historical:
    get:
      summary: Get historical sensor data
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: List of historical data
  /api/alerts:
    get:
      summary: Get active alerts
      responses:
        '200':
          description: List of alerts
  /api/status:
    get:
      summary: Get system status
      responses:
        '200':
          description: System status
